#!/bin/python3
import argparse;
import subprocess as proc;
import os;
import hashlib;
import pickle;
import tempfile;
import multiprocessing as mp;
import time;
import shutil;
import json;
from pathlib import Path;

mp.set_start_method("fork")

# This is used to build and test the compiler only.
# Large part of the scripts are generated by ChatGPT and Deepseek.

parser = argparse.ArgumentParser()
parser.add_argument("-r", "--run", action="store_true")
parser.add_argument("--rebuild", action="store_true")
parser.add_argument("-d", "--objdump", type=str)

args = parser.parse_args()

SRC_DIR = Path("src")
BUILD_DIR = Path("build")
FINAL_BINARY = BUILD_DIR / "kernel"
COMPILER = "riscv64-unknown-elf-g++"
AR = "riscv64-unknown-elf-ar"
CFLAGS = [
  "-x", "c", "-c", "-std=c11", "-O2",
  "-Wall", "-Wextra", "-Wuninitialized", "-fno-strict-aliasing",
  "-ffreestanding", "-nostdlib",
  "-mcmodel=medany", "-march=rv64gc", "-mabi=lp64"
]
CXXFLAGS = [
  "-x", "c++", "-c", "-std=c++20", "-O2",
  "-Wall", "-Wextra", "-Wuninitialized", "-fno-strict-aliasing",
  "-ffreestanding", "-nostdlib", "-fno-rtti", "-fno-exceptions",
  "-mcmodel=medany", "-march=rv64gc", "-mabi=lp64"
]
SFLAGS = [
  "-c", "-ffreestanding", "-nostdlib",
  "-mcmodel=medany", "-march=rv64gc", "-mabi=lp64"
]
LDFLAGS = ["-T", "link.ld", "-nostdlib", "-mcmodel=medany"]
CACHE_FILE = BUILD_DIR / ".build_cache.pkl"
INCLUDE_CACHE_FILE = BUILD_DIR / ".include_cache.pkl"
INITRAMFS_PATH = SRC_DIR / "fs/init"

def hash_file(path):
  h = hashlib.sha256()
  with open(path, 'rb') as f:
    h.update(f.read())
  return h.hexdigest()

def find_files() -> tuple[list[Path], list[Path]]:
  cpp_files = []
  h_files = []
  for path in SRC_DIR.rglob("*"):
    if path.is_relative_to(INITRAMFS_PATH):
      continue
    if path.suffix in [".cpp", ".c", ".s"]:
      cpp_files.append(path)
    elif path.suffix == ".h":
      h_files.append(path)
  return cpp_files, h_files

def load_cache():
  if CACHE_FILE.exists():
    with open(CACHE_FILE, "rb") as f:
      return pickle.load(f)
  return {}

def save_cache(cache):
  BUILD_DIR.mkdir(parents=True, exist_ok=True)
  with open(CACHE_FILE, "wb") as f:
    pickle.dump(cache, f)

def needs_recompile(src_path, obj_path, cache, dependencies):
  src_hash = hash_file(src_path)
  dep_hashes = { str(dep): hash_file(dep) for dep in dependencies }

  prev = cache.get(str(src_path))
  if not prev:
      return True
  if prev['src_hash'] != src_hash:
      return True
  if prev['dep_hashes'] != dep_hashes:
      return True
  if not obj_path.exists():
      return True
  return False

include_cache = {}
include_hashes = {}

def load_include_cache():
  if INCLUDE_CACHE_FILE.exists():
    with open(INCLUDE_CACHE_FILE, "rb") as f:
      return pickle.load(f)
  return {}

def save_include_cache(cache):
  BUILD_DIR.mkdir(parents=True, exist_ok=True)
  with open(INCLUDE_CACHE_FILE, "wb") as f:
    pickle.dump(cache, f)

def get_all_includes(src_path: Path, visited=None) -> set[Path]:
  if visited is None:
    visited = set()

  resolved_path = src_path.resolve()
  if resolved_path in visited:
    return set()

  visited.add(resolved_path)
  file_hash = hash_file(resolved_path)

  cached_entry = include_cache.get(resolved_path)
  if cached_entry and include_hashes.get(resolved_path) == file_hash:
    return cached_entry

  includes = set()

  with open(resolved_path, "r") as f:
    for line in f:
      line = line.strip()
      if line.startswith("#include \""):
        header = line.split("\"")[1]
        include_path = resolved_path.parent / header
        if include_path.exists():
          includes.add(include_path.resolve())
          includes.update(get_all_includes(include_path, visited))

  include_cache[resolved_path] = includes
  include_hashes[resolved_path] = file_hash
  return includes

flagmap = {
  ".cpp": CXXFLAGS,
  ".c" : CFLAGS,
  ".s" : SFLAGS
}

def get_flags(path: Path):
  return flagmap[path.suffix]

def compile_file(src_path: Path, obj_path: Path):
  obj_path.parent.mkdir(parents=True, exist_ok=True)
  src = str(src_path)
  proc.check_call([COMPILER, *get_flags(src_path), "-o", str(obj_path), src])

def compile_initramfs(src_path: Path, obj_path: Path):
  obj_path.parent.mkdir(parents=True, exist_ok=True)
  proc.check_call([COMPILER, "-ffreestanding", "-nostdlib",
  "-mcmodel=medany", "-march=rv64gc", "-mabi=lp64", "-o", str(obj_path),  str(src_path)])

def archive_objects(obj_files, lib_path: Path):
  if lib_path.exists():
    lib_path.unlink()
  print(f"Creating archive {lib_path}")
  proc.check_call([AR, "rcs", str(lib_path)] + [str(obj) for obj in obj_files])

def link_libraries(lib_files, output_binary):
  print(f"Linking {output_binary}")
  result = proc.run([COMPILER] + LDFLAGS + ["-o", str(output_binary)] + ["-Wl,--start-group"] + [str(lib) for lib in lib_files] + ["-Wl,--end-group"], stderr=proc.PIPE)
  # Manually ignore a warning.
  for line in result.stderr.decode("utf-8").split("\n"):
    if line.find("warning: build/kernel has a LOAD segment with RWX permissions") != -1:
      continue
    print(line)

  if result.returncode != 0:
    os._exit(1)
  

def build_initramfs():
  tasks: list[tuple[Path, Path]] = []
  cache = load_cache()
  for file in INITRAMFS_PATH.rglob("*"):
    obj_dir = BUILD_DIR / "initramfs"
    obj_path = obj_dir / (file.stem)
    if needs_recompile(file, obj_path, cache, dependencies={}):
      tasks.append((file, obj_path))
  total = len(tasks)
  file_prompt = "file" if total == 1 else "files"
  if total > 0:
    print(f"Bundling {total} {file_prompt}")
  with mp.Pool() as pool:
    pool.starmap(compile_initramfs, tasks)
  proc.check_call(f"find {obj_dir} -print0 | cpio --null -oH newc > {BUILD_DIR}/initramfs.cpio 2> /dev/null", shell=True)

def build():
  build_initramfs()

  global include_cache, include_hashes
  include_cache_data = load_include_cache()
  include_cache = include_cache_data.get("cache", {})
  include_hashes = include_cache_data.get("hashes", {})

  cpp_files, _ = find_files()
  cache = load_cache()

  # Generate compile_commands.json.
  commands = []
  for file in cpp_files:
    absolute = str(file.absolute())
    flags = [x for x in get_flags(file) if x not in ["-mcmodel=medany", "-march=rv64gc", "-mabi=lp64"]]
    commands.append({
      "directory": os.path.abspath("."),
      "file": absolute,
      "command": f"clang++ {' '.join(flags)} -c {absolute}"
    })
    
  with open("compile_commands.json", "w") as conf:
    json.dump(commands, conf, indent=2)

  # Step 1: Compile .cpp to .o
  obj_files: list[tuple[Path, Path]] = []
  folder_changed: dict[Path, bool] = {}
  tasks: list[tuple[Path, Path]] = []
  for cpp in cpp_files:
    rel_dir = cpp.relative_to(SRC_DIR).parent
    obj_dir = BUILD_DIR / rel_dir
    obj_path = obj_dir / (cpp.stem + ".o")

    dependencies = get_all_includes(cpp)
    if needs_recompile(cpp, obj_path, cache, dependencies):
      tasks.append((cpp, obj_path))
      cache[str(cpp)] = {
        'src_hash': hash_file(cpp),
        'dep_hashes': {str(dep): hash_file(dep) for dep in dependencies},
      }
      folder_changed[rel_dir] = True
    obj_files.append((rel_dir, obj_path))

  total = len(tasks)
  file_prompt = "file" if total == 1 else "files"
  if total > 0:
    print(f"Compiling {total} {file_prompt}")
  with mp.Pool() as pool:
    pool.starmap(compile_file, tasks)
  
  save_cache(cache)

  # Step 2: Archive .o's in same folder into .a
  folder_objs = {}
  for rel_dir, obj in obj_files:
    folder_objs.setdefault(rel_dir, []).append(obj)

  lib_files = []
  for folder, objs in folder_objs.items():
    lib_path = BUILD_DIR / folder / (folder.name + ".a")
    need_archive = folder_changed.get(folder, False) or not lib_path.exists()
    if need_archive:
      archive_objects(objs, lib_path)
    lib_files.append(lib_path)

  # Step 3: Link all .a's into final binary
  link_libraries(lib_files, FINAL_BINARY)

  save_include_cache({
    "cache": include_cache,
    "hashes": include_hashes
  })

if __name__ == "__main__":
  if args.rebuild:
    shutil.rmtree(BUILD_DIR)

  build()
  if args.objdump:
    proc.run(f"riscv64-unknown-elf-objdump -d {args.objdump}", shell=True)
    exit(0)

  if args.run:
    proc.check_call(f"qemu-system-riscv64 -nographic -machine virt -bios default -kernel {BUILD_DIR}/kernel -initrd {BUILD_DIR}/initramfs.cpio", shell=True)
  print("Run finished.")
